### ISSUE TITLE
The calculator apps is not working correctly. EOS 5.1.4

### ISSUE THREAD

**Issue by Artist6481** [elementary/calculator#132] opened 2020-06-02 12:43 UTC
When subtracting percent of an integer, the answer is incorrect.
100−10% = 99,9

**Comment by lewisgoddard** [comment] 2020-06-02 12:46
Duplicate of #44

**Comment by Exalm** [comment] 2020-06-02 15:19
But that's the correct answer? 10% == 0.01, 100 - 0.01 = 99.9

**Comment by parnold-x** [comment] 2020-06-02 15:27
> But that's the correct answer? 10% == 0.01, 100 - 0.01 = 99.9

Nope, 10% is 0.1

**Comment by Exalm** [comment] 2020-06-02 15:28
Oops 🤦️ And made the same typo 2 times even. But you get the idea, 99.9 is the expected answer.

**Closed** 2020-06-02 16:48 UTC
Labels: Status: Duplicate
