### ISSUE TITLE
Clicking expand button enlarges all open windows

### ISSUE THREAD

**Issue by hanaral** [elementary/calculator#182] opened 2021-05-15 13:49 UTC
## What Happened

Opening multiple windows and clicking 'Show extended functionality' causes all of them to expand rather than the focused one. This is laggy af for me even on my ryzen system

## Expected Behavior

Only the focused window expands

## Steps to Reproduce

1. Open multiple calculator windows
2. Click expand button on one of them

## Platform Information

elementary OS 6 Early Access, up to date calculator

**Comment by jeremypw** [comment] 2021-05-15 15:49
That might not be so easy - all the windows are bound to the setting "extended-shown".  I guess that the setting should only be bound to the first window as that is the only one restored.  It shouldn't be laggy though unless it is the multiple animations happening simultaneously (?)  I presume that with one window there is no lag?

**Comment by jeremypw** [comment] 2021-05-15 15:52
I can't seem to install Calculator at the moment from AppCenter - maybe something to do with it being in the process of being flatpak'd (that would probably slow down responding to setting changes as well)

**Comment by jeremypw** [comment] 2021-05-15 16:00
OK, I installed system-wide and can confirm that the animation is a little jerky when three windows are open. Not sure how many people routinely open multiple calculators though.

**Comment by ryonakano** [comment] 2021-08-20 12:43
Did #192 fix the issue?

**Comment by lenemter** [comment] 2023-01-05 10:50
I cannot reproduce the issue, seems like it was fixed in #192.

**Closed by lenemter** 2023-01-05 10:50 UTC
Labels: Priority: Low, Status: Confirmed
