### ISSUE TITLE
Calculator UI has bug in view

### ISSUE THREAD

**Issue by PouyaPouryaie** [elementary/calculator#243] opened 2023-03-12 00:07 UTC
### What Happened?

![calculator](https://user-images.githubusercontent.com/9164303/224516999-eec284fc-b441-4e93-8fbd-6650d9aaadfb.png)

It seems the calculator has not good arrange in view and has an extra column at the end of the right side in normal view

### Steps to Reproduce

I just open it and see this problem exist for me.

### Expected Behavior

I think the calculator view seems like this picture:
![write-calculator](https://user-images.githubusercontent.com/9164303/224517074-1b225e17-0216-4d51-9afa-9d700683aba0.png)

### OS Version

7.x (Horus)

### Software Version

Latest release (I have run all updates)

**Comment by lenemter** [comment] 2023-03-12 02:24
Hello. This is a duplicate of #236 which has been fixed, and fix will be included in the next release.

**Closed by lenemter** 2023-03-12 02:24 UTC
