### ISSUE TITLE
Can't start typing directly on start because it is focusing to expand button. 

### ISSUE THREAD

**Issue by queeup** [elementary/calculator#198] opened 2021-08-24 22:49 UTC
## What Happened

Calculator is starting focused to expand button. That's why I can't start typing or use it just with keyboard. I need to click to number area or hit `Tab` button on the keyboard.

![calculator_wrong_focus](https://user-images.githubusercontent.com/87835/130699906-273ff21c-926b-48ab-b85d-65ae48e82a62.png)

## Expected Behavior

Open it and start typing. Focusing on the number area at the beginning.

## Steps to Reproduce

1. Open it and start writing some numbers.

### Logs

N/A

## Platform Information

elementary Odin

**Comment by queeup** [comment] 2021-08-24 22:49
Related: #157

**Comment by ryonakano** [comment] 2021-08-25 03:55
Duplicate of #195 and fixed in #197.

**Closed by ryonakano** 2021-08-25 03:55 UTC
