### ISSUE TITLE
App does not get focus when started from the Applications menu

### ISSUE THREAD

**Issue by KowalskiThomas** [elementary/calculator#95] opened 2019-04-24 11:53 UTC
Using the calculator pretty often, I have found a bug that is quite annoying.

When starting the Calculator from the Applications menu (Ctrl + Space > `calc` > Enter), the application does not get focused on. For some reason, it is the application that was already focused that keeps it, which forces the user to first click on the Calculator window, and then type the expression.

After trying with other elementary OS apps (Code for example, but also AppCenter), I have found the Calculator to be the only one affected by this problem, hence I concluded that the issue came from the Calculator application itself, and not the OS.

**Comment by peteruithoven** [comment] 2019-04-24 12:06
Thanks for the report! I'm afraid this is a duplicate of https://github.com/elementary/calculator/issues/91 or https://github.com/elementary/applications-menu/issues/19
Please make sure to search before you post.

**Closed by peteruithoven** 2019-04-24 12:06 UTC
