### ISSUE TITLE
No keyboard focus on start

### ISSUE THREAD

**Issue by kbondarev** [elementary/calculator#91] opened 2019-02-24 01:42 UTC
When the app is being opened it does not receive "focus", meaning if I start typing it doesn't get my input until I click the window with the mouse pointer.
This is very inconvenient as when I need to do a quick calculations I am opening the app through keyboard only (Super + space, type "calc", press enter) and expect to continue typing my calculations.

**Comment by peteruithoven** [comment] 2019-02-24 01:55
Thanks for the report! I'm afraid this is a duplicate of https://github.com/elementary/applications-menu/issues/19

**Closed by peteruithoven** 2019-02-24 01:55 UTC
